# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

# Overwrite or add rules to create your own house style
#
# # Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
# Layout/SpaceInsideArrayLiteralBrackets:
#   Enabled: false
#

AllCops:
  NewCops: enable


Bundler:
  Enabled: true
Gemspec:
  Enabled: true
Layout:
  Enabled: true
Layout/EndAlignment:
  Enabled: true
  EnforcedStyleAlignWith: keyword
Lint:
  Enabled: true
Metrics:
  Enabled: true
Naming:
  Enabled: true
Performance:
  Enabled: true
  Exclude:
    - "test/**/*"
Rails:
  Enabled: true
Security:
  Enabled: true
Style:
  Enabled: true
Style/Documentation:
  Enabled: false
