# frozen_string_literal: true

# Autogenerated configuration for Caber
Caber.configure do |config|
  # List the object-level permissions you want
  config.permissions = %w[
    owner
    admin
    support
    driver
  ]
end
