# frozen_string_literal: true

require "active_support/concern"
require "cuid2"

# CuidId extends ActiveRecord to use a cuid2 id generated by the application instead of the db
module CuidId
  extend ActiveSupport::Concern

  included do
    before_create :generate_id
  end

  private

  def generate_id
    self.id = Cuid2.generate if self.class.type_for_attribute("id").type == :string
  end
end

ActiveSupport.on_load(:active_record) { include CuidId }
